name: 'ghascompliance'
description: 'ghascompliance'

inputs:
  severity:
    description: 'Severity Level'
    default: error

  repository:
    description: Repository owner and repo name
    default: ${{ github.repository }}

  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}
  
  ref:
    description: GitHub Ref
    default: ${{ github.ref }}

  action:
    description: 'Action to take upon discovery of security issues hitting threshold'
    default: break

  policy:
    description: Policy as Code repository owner/repo name

  policy-path:
    description: Policy as Code file path (including path in repo)

  policy-branch:
    description: Policy as Code branch
    default: main


  argvs:
    description: 'Additional Arguments'


runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Installing Dependencies"
        pushd ${{ github.action_path }}
        python3 -m pip install pipenv && python3 -m pipenv install --system
        popd
        echo "::endgroup::"
    - shell: bash
      run: |
        echo "::error ::This Action has been moved to `advanced-security/policy-as-code`"
        echo "::error ::The Action is pinned to 1.7.0 and will no longer receive any updates going forward"

        PYTHONPATH=${{ github.action_path }} && export PYTHONPATH=${{ github.action_path }}
        python3 -m ghascompliance \
          --severity "${{ inputs.severity }}" \
          --action "${{ inputs.action }}" \
          --github-token "${{ inputs.token }}" \
          --github-repository "${{ inputs.repository }}" \
          --github-ref "${{ inputs.ref }}" \
          --github-policy "${{ inputs.policy }}" \
          --github-policy-path "${{ inputs.policy-path }}" \
          --github-policy-branch "${{ inputs.policy-branch }}" \
          ${{ inputs.argvs }}
